TILEWIDTH = 25
TILEHEIGHT = 25
ROWS = 24
COLS = 32
LARGER_SCREENWIDTH = 800
LARGER_SCREENHEIGHT = 800
SCREENWIDTH = COLS * TILEWIDTH 
SCREENHEIGHT = ROWS * TILEHEIGHT 

OFFSET_X = (LARGER_SCREENWIDTH - SCREENWIDTH) // 2
OFFSET_Y = (LARGER_SCREENHEIGHT - SCREENHEIGHT)// 2


SCREENSIZE = (LARGER_SCREENHEIGHT,LARGER_SCREENHEIGHT)

LIGHT_BLUE = (0, 165, 0)
BLACK = (0, 0, 0)
YELLOW = (255, 255, 0)
WHITE = (255,255,255)
RED = (150,0,0)
CYAN = (120,255,255)

PACMAN = "PACMAN"
PELLET = 1
POWERPELLET = 2
GHOST = 3

# Directions
STOP = 0
UP = 1
DOWN = -1
LEFT = 2
RIGHT = -2
PORTAL = 3

# Ghost behaviours
SCATTER = "scatter"
CHASE = "chase"
FRIGHT = "frightened"
SPAWN = 3

# Ghost home values
home_x_start = 9
home_y_start = 10



